### PR TITLE
[FEAT] Implements basic gravity and jump physics

### PR DESCRIPTION
**Pull request by benheller**
## Features
1. Basic gravity using https://github.com/donmccurdy/aframe-physics-system
1. Jump physics using https://github.com/donmccurdy/aframe-extras (press spacebar)

This will make the user "fall" from the mortal plane into the innerverse plane, where the gray house will be positioned.

## Questions
1. We can add collision physics to other objects (right now it's enabled only on the two planes). Do we want to collide with any of the house artifacts or other objects? If so, which ones?
1. You'll note that the player bounces when hitting the lower platform. Is the "bounciness" too high?

## Issues
1. Due to [this bug](https://github.com/donmccurdy/aframe-extras/issues/225) there's a slight jitter to the player. I'm going to see if I can fork this package and fix it, but in the meantime:
    - Is this acceptable? If not, we should seek another library or re-implement `kinematic-body` as a navmesh.
    - Would it be acceptable if we somehow made it much worse and therefore intentional?

### CODE REVIEW

**Comment by davclark** [comment]
This is great. I will test on Gear VR, and my guess is that since it's actually gotten slower on it's own (and laggy / tear-y), this will be hard for the Gear. But who knows?

I don't suppose this is staged anywhere right now?

**Comment by davclark** [comment]
Also it would be great if we could get Arash or Nate to test on their Vive. I don't think Nate uses GitHub, so we'd definitely need to stage for him.

PS - Windows MR headset from Samsung (best one currently) is on a major sale for $300. I'm sorely tempted.

**Comment by sbenthall** [comment]
This is amazing.

Q1. I think it's up to each house how dynamic or static they want their facade to be. You could demo the functionality by adding a dynamic object to your house facade. That would be really nice, because currently the High House facade is the worst house facade, totally not living up to its potential and destiny as the Highest House.

Q1.1 I wonder how the physics enginer interacts with the normal Aframe animation flags. Does an animated "moving" static platform still have things collide off of it?* What happens when a dynamic object is animated?

Q2. I don't really notice the bounce. Seems fine to me.

I1. I think the jitter is OK, but I'm not really sure what the jumping functionality is getting us at the moment.

I1.1 I think it would be very nice if we could have a series of animated, floating, 'static' platforms that allow the user to jump higher and higher to get a prize. Maybe that's a new issue though?

Other notes:

1. I definitely love the way that if I nihilisticly throw myself off of the edge of the Innerverse, I fall out of the known spectral universe and I just see the whole Orbis Develandus turn into blank, white, nothingness. It really works.

2. I think this is a totally mission critical change and that it opens up a lot of possibilities, and so should be adopted ASAP.

**Comment by sbenthall** [comment]
@davclark Does Nate know how to check out a pull request and stage it himself? otherwise, I'm inclined to push this into 'production' so he can get to it via webVR normally. I think Ash is traveling now?

**Comment by sbenthall** [comment]
Thanks for this Ben!!

**Pull request merged**
